version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0
      # - image: 'existdb/existdb:latest'
      #   auth:
      #     username: duncdrum
      #     password: $DOCKER_TMP_PW
      # - image: 'existdb/existdb:5.0.0'
      #   auth:
      #     username: duncdrum
      #     password: $DOCKER_TMP_PW
      # - image: 'existdb/existdb:5.2.0'
      #   auth:
      #     username: duncdrum
      #     password: $DOCKER_TMP_PW        
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: install
          command: mvn -B -V -q -Ddocker.skip=true -Dexec.skip=true -DskipTests=true -Dmaven.javadoc.skip=true install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}            
  # test:
  #   docker:
  #     - image: cimg/openjdk:8.0
      # - image: 'existdb/existdb:latest'
      #   auth:
      #     username: duncdrum
      #     password: $DOCKER_TMP_PW
    # steps:        
      - run:
          name: verify
          command: mvn  -B -V -q -Ddocker.test.port=8080 -Ddocker.test.image=existdb/existdb:latest verify

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      # - test:
      #     requires:
      #           - build   

      # TODO (DP): 
      #   -  add env variables, and secrets in circle
      #   -  configure dockerize https://circleci.com/docs/2.0/databases/#using-dockerize-to-wait-for-dependencies
      # see https://github.com/evolvedbinary/fusion-studio-api/issues/30
      # see https://circleci.com/developer/orbs/orb/circleci/maven orb config
