version: 2.1
docker:
  - image: 'cimg/openjdk:8.0'
orbs:
  maven: circleci/maven@1.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'verify -Ddocker.test.port=$FS_API_PORT -Ddocker.test.image=$DOCKER_TEST_IMAGE -B'

      # mvn install -Ddocker.skip=true -Dexec.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      # mvn verify -Ddocker.test.port=$FS_API_PORT -Ddocker.test.image=$DOCKER_TEST_IMAGE -B
