version: 2.1

# xenial uses Java 8 by default we need a VM executor for now
executors:
  xenial:
    machine:
      image: ubuntu-1604:202007-01

# see https://circleci.com/developer/orbs/orb/circleci/maven orb config
# next up inline orbing it:
# see https://circleci.com/docs/2.0/reusing-config/#writing-inline-orbs
orbs:
  maven: circleci/maven@1.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          matrix:
            parameters:
              command: 
                - 'verify -B -q -Dapi.port=8080 -Ddocker.db.image=existdb/existdb:latest'
                - 'verify -B -q -Dapi.port=8080 -Ddocker.db.image=existdb/existdb:5.2.0'
                - 'verify -B -q -Dapi.port=8080 -Ddocker.db.image=existdb/existdb:5.0.0'
                - 'verify -B -q -Ddocker.username=$FDB_NIGHTLY_DOCKER_USER -Ddocker.password=$FDB_NIGHTLY_DOCKER_PASS'
                # - 'verify -B -q -Ddocker.username=$FDB_DOCKER_USER -Ddocker.password=$FDB_DOCKER_PASS -Ddocker.db.image=repo.evolvedbinary.com:9443/evolvedbinary/fusiondb-server:latest'
          executor: 'xenial'    
          context:
            - FusionStudio
            - FusionDB_images
          test_results_path: target/failsafe-reports
   


