version: 2.1

#orbs:
#  slack: circleci/slack@4.3.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
  build_cmd:
    steps:
      - run: mvn install -Ddocker.skip=true -Dexec.skip=true -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  verify_fdb_nightly_cmd:
    steps:
      - run:
          environment:
            FS_API_PORT: 4059
          command: mvn verify -Ddocker.test.port=4059 -Ddocker.test.image=repo.evolvedbinary.com:9543/evolvedbinary/fusiondb-server:nightly -Ddocker.username=$FDB_NIGHTLY_DOCKER_USER -Ddocker.password=$FDB_NIGHTLY_DOCKER_PASS -B
  verify_fdb_release_cmd:
    steps:
      - run:
          environment:
            FS_API_PORT: 4059
          command: mvn verify -Ddocker.test.port=4059 -Ddocker.test.image=repo.evolvedbinary.com:9443/evolvedbinary/fusiondb-server:1.0.0-ALPHA3 -Ddocker.username=$FDB_DOCKER_USER -Ddocker.password=$FDB_DOCKER_PASS -B
  verify_public_repo_cmd:
    parameters:
      db_server_docker_image:
        description: The identifier of a Docker Image which runs the database server
        type: string
      db_server_port:
        description: The TCP port number for the database server in the Docker Image
        type: integer
    steps:
      - run:
          environment:
            FS_API_PORT: << parameters.db_server_port >>
          command: mvn verify -Ddocker.test.port=<< parameters.db_server_port >> -Ddocker.test.image=<< parameters.db_server_docker_image >> -B

executors:
  linux-executor:
    machine:
      image: ubuntu-2004:202101-01

jobs:
  build-and-verify-with-fdb-nightly:
    executor: linux-executor
    steps:
      - checkout
      - restore_cache_cmd
      - build_cmd
      - verify_fdb_nightly_cmd
      - save_cache_cmd
  #      - slack/notify:
  #          channel: dev
  #          event: fail
  #          template: basic_fail_1
  build-and-verify-with-fdb-release:
    executor: linux-executor
    steps:
      - checkout
      - restore_cache_cmd
      - build_cmd
      - verify_fdb_release_cmd
      - save_cache_cmd
    #      - slack/notify:
    #          channel: dev
    #          event: fail
    #          template: basic_fail_1
  build-and-verify-with-existdb:
    parameters:
      existdb_docker_image_version:
        description: The version of the eXist-db Docker Image
        type: string
    executor: linux-executor
    steps:
      - checkout
      - restore_cache_cmd
      - build_cmd
      - verify_public_repo_cmd:
          db_server_docker_image: existdb/existdb:<< parameters.existdb_docker_image_version >>
          db_server_port: 8080
      - save_cache_cmd
#      - slack/notify:
#          channel: dev
#          event: fail
#          template: basic_fail_1

workflows:
  build-and-verify:
    jobs:
      - build-and-verify-with-fdb-nightly:
          name: "Build and Verify for FusionDB Nightly"
          context: FusionDB_images
      - build-and-verify-with-fdb-release:
          name: "Build and Verify for FusionDB 1.0.0-ALPHA3"
          context: FusionDB_images
      - build-and-verify-with-existdb:
          name: "Build and Verify for eXist-db"
          matrix:
            parameters:
              existdb_docker_image_version: ["latest", "5.2.0", "5.0.0" ]
